#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: sakshimishra
  CLOUD_SQL_PASSWORD: sakshi
  CLOUD_SQL_DATABASE_NAME: form
  CLOUD_SQL_CONNECTION_NAME: project-gcp-340906:asia-south1:sample-form
  
