#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: surabhi
  CLOUD_SQL_PASSWORD: 12345
  CLOUD_SQL_DATABASE_NAME: test-db
  CLOUD_SQL_CONNECTION_NAME: flaskproject-341104:us-central1:test-instance
  
